import { onSchedule } from 'firebase-functions/v2/scheduler';
import { Timestamp } from 'firebase-admin/firestore';
import { db } from '../firebase.js';
import { callTextAnalysis, getAiProvider } from './ai.js';
import { calculateHabitCorrelations, summarizeHabitLogs } from './habits.js';
import { loadHabitLogs, loadJournalEntries, loadYearEntries } from './loaders.js';
import { localTextAnalysis } from './local-analysis.js';
import {
  average,
  dailyRatingPoints,
  longestStreak,
  previousMonthRange,
  trendSlope,
  variance,
} from './stats.js';
import type {
  CalculatedHabitCorrelation,
  HabitInsightLog,
  JournalInsightEntry,
} from './types.js';
import { isRemoteAnalysis } from './types.js';

export async function buildInsight(
  entries: JournalInsightEntry[],
  habitLogs: HabitInsightLog[],
) {
  const points = dailyRatingPoints(entries);
  const ratings = points.map((point) => point.rating);
  const habitSummary = summarizeHabitLogs(habitLogs);
  const habitCorrelations = calculateHabitCorrelations(entries, habitSummary);

  const contentEntries = entries.filter((e) => e.content.trim().length > 0);
  const textAnalysis =
    contentEntries.length > 0
      ? await callTextAnalysis(contentEntries, habitCorrelations)
      : localTextAnalysis(entries);

  const localAnalysis = isRemoteAnalysis(textAnalysis) ? textAnalysis.fallback : textAnalysis;
  const periodAverage = average(ratings) ?? 3;
  const programmaticFactors = Object.entries(localAnalysis.topicAverages)
    .filter(([_, data]) => data.count >= 2)
    .map(([topic, data]) => {
      const topicAvg = data.averageRating ?? 3;
      const diff = topicAvg - periodAverage;
      const threshold = 0.15;
      return {
        factor: topic.replace(/([A-Z])/g, ' $1').toLowerCase().trim(),
        impact: diff > threshold ? 'positive' : diff < -threshold ? 'negative' : 'neutral',
        averageRating: topicAvg,
      };
    })
    .sort((a, b) => (b.averageRating ?? 0) - (a.averageRating ?? 0));

  // Secure programmatic merging: Ensures mathematically accurate data is married safely
  // with qualitative sentence structure generated by the AI provider.
  let mergedCorrelations: CalculatedHabitCorrelation[] = habitCorrelations.map((calc) => ({
    ...calc,
    insight: 'No qualitative analysis generated.',
  }));

  if (isRemoteAnalysis(textAnalysis)) {
    const aiResult = textAnalysis.result as Record<string, unknown> & {
      habitCorrelations?: Array<{ habit?: string; insight?: string }>;
    };

    if (aiResult) {
      // OVERRIDE: Replace AI's guessed factors with our data-driven ones
      aiResult.ratingCorrelations = programmaticFactors;

      if (Array.isArray(aiResult.habitCorrelations)) {
        mergedCorrelations = habitCorrelations.map((calc) => {
          const matchingLLM = aiResult.habitCorrelations?.find(
            (h) =>
              typeof h.habit === 'string' &&
              h.habit.toLowerCase() === calc.habitName.toLowerCase(),
          );
          return {
            ...calc,
            insight: matchingLLM?.insight || 'No qualitative analysis generated.',
          };
        });
      }
    }
  } else {
    // If we're using local fallback, add the programmatic factors to the result
    (textAnalysis as Record<string, unknown>).ratingCorrelations = programmaticFactors;
  }

  return {
    entryCount: entries.length,
    ratedDayCount: points.length,
    averageRating: average(ratings),
    trendSlopePerDay: trendSlope(points),
    variance: variance(ratings),
    streaks: {
      longestHighDays: longestStreak(points, (rating) => rating >= 4),
      longestLowDays: longestStreak(points, (rating) => rating <= 2),
    },
    dailyRatings: points,
    textAnalysis,
    habitCorrelations: mergedCorrelations, // Now located at the root for guaranteed structural integrity
    habitSummary,
  };
}

export const compileJournalHappinessInsights = onSchedule(
  {
    schedule: '0 13 2 * *',
    timeZone: 'UTC',
    memory: '512MiB',
    timeoutSeconds: 540,
    secrets: ['GROQ_API_KEY', 'GEMINI_API_KEY', 'OWNER_UID'],
  },
  async () => {
    const ownerUid = process.env.OWNER_UID;

    if (!ownerUid) {
      throw new Error('OWNER_UID secret is not set — cannot compile insights');
    }

    console.log(`AI provider: ${getAiProvider()}`);

    const range = previousMonthRange();
    console.log(`Processing insights for period: ${range.key}`);

    const entries = await loadJournalEntries(range.start, range.end, ownerUid);

    if (entries.length === 0) {
      console.log('No journal entries found for this period — skipping insight generation');
      return;
    }

    console.log(`Building insights for ${ownerUid} (${entries.length} entries)`);

    try {
      const monthHabitLogs = await loadHabitLogs(range.start, range.end, ownerUid);
      const monthInsight = await buildInsight(entries, monthHabitLogs);
      const yearEntries = await loadYearEntries(ownerUid, range.year);
      const yearStart = new Date(Date.UTC(range.year, 0, 1));
      const yearEnd = new Date(Date.UTC(range.year + 1, 0, 1));
      const yearHabitLogs = await loadHabitLogs(yearStart, yearEnd, ownerUid);
      const yearInsight = await buildInsight(yearEntries, yearHabitLogs);

      await db
        .collection('insights')
        .doc(ownerUid)
        .collection('monthly')
        .doc(range.key)
        .set({
          period: range.key,
          periodStart: Timestamp.fromDate(range.start),
          periodEnd: Timestamp.fromDate(range.end),
          generatedAt: Timestamp.now(),
          monthly: monthInsight,
          yearToDate: yearInsight,
        });

      await db
        .collection('insights')
        .doc(ownerUid)
        .collection('yearly')
        .doc(String(range.year))
        .set(
          {
            year: range.year,
            generatedAt: Timestamp.now(),
            yearly: yearInsight,
          },
          { merge: true },
        );

      console.log(`✅ Successfully compiled insights for ${ownerUid}`);
    } catch (error) {
      console.error(`❌ Failed to compile journal happiness insights for ${ownerUid}`, error);
      throw error;
    }
  },
);
